from . import crud_router
from . import crud_isp
from . import crud_cliente
from . import crud_servico
from . import crud_servico_contratado
from . import crud_empresa
from . import crud_nfcom
from . import crud_usuario
from . import crud_radius
from . import crud_password_reset
from . import crud_network
from . import crud_network
from . import crud_subscription