"""Increase sicredi_posto column length

Revision ID: 048fa59aa4ae
Revises: 824a7ae9e576
Create Date: 2025-12-08 13:49:43.454343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '048fa59aa4ae'
down_revision: Union[str, Sequence[str], None] = '824a7ae9e576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'sicredi_posto',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'sicredi_posto',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
