"""Change Receivable bank to String and update Bank enum

Revision ID: 0b6f817c2fbb
Revises: 415f86c312a2
Create Date: 2026-05-07 13:36:17.593977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b6f817c2fbb'
down_revision: Union[str, Sequence[str], None] = '415f86c312a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('uq_clientes_empresa_cpf_cnpj'), table_name='clientes')
    # op.create_index(op.f('ix_password_reset_tokens_cliente_id'), 'password_reset_tokens_cliente', ['id'], unique=False)
    op.alter_column('receivables', 'bank',
               existing_type=mysql.ENUM('SICOB', 'SICREDI', 'OUTRO'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'SICOB'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receivables', 'bank',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('SICOB', 'SICREDI', 'OUTRO'),
               existing_nullable=False,
               existing_server_default=sa.text("'SICOB'"))
    # op.drop_index(op.f('ix_password_reset_tokens_cliente_id'), table_name='password_reset_tokens_cliente')
    # op.create_index(op.f('uq_clientes_empresa_cpf_cnpj'), 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
