"""Change Receivable status to String and update BoletoStatus enum

Revision ID: 0fd7e7f85789
Revises: 0b6f817c2fbb
Create Date: 2026-05-07 13:38:01.303056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fd7e7f85789'
down_revision: Union[str, Sequence[str], None] = '0b6f817c2fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('uq_clientes_empresa_cpf_cnpj'), table_name='clientes')
    # op.create_index(op.f('ix_password_reset_tokens_cliente_id'), 'password_reset_tokens_cliente', ['id'], unique=False)
    op.alter_column('receivables', 'status',
               existing_type=mysql.ENUM('PENDING', 'REGISTERED', 'PRINTED', 'SENT', 'PAID', 'CANCELLED', 'REJECTED'),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receivables', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('PENDING', 'REGISTERED', 'PRINTED', 'SENT', 'PAID', 'CANCELLED', 'REJECTED'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    # op.drop_index(op.f('ix_password_reset_tokens_cliente_id'), table_name='password_reset_tokens_cliente')
    # op.create_index(op.f('uq_clientes_empresa_cpf_cnpj'), 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
