"""Add fields to BankAccount for billing integration

Revision ID: 158b24a98a89
Revises: 048fa59aa4ae
Create Date: 2026-05-07 11:30:57.063842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158b24a98a89'
down_revision: Union[str, Sequence[str], None] = '048fa59aa4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('bank_accounts', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('bank_accounts', sa.Column('cnab_version', sa.String(length=10), nullable=True))
    op.add_column('bank_accounts', sa.Column('carteira_variacao', sa.String(length=10), nullable=True))
    op.add_column('bank_accounts', sa.Column('instrucao1', sa.String(length=255), nullable=True))
    op.add_column('bank_accounts', sa.Column('instrucao2', sa.String(length=255), nullable=True))
    op.add_column('bank_accounts', sa.Column('dias_protesto', sa.Integer(), nullable=True))
    op.add_column('bank_accounts', sa.Column('dias_baixa', sa.Integer(), nullable=True))
    op.add_column('bank_accounts', sa.Column('bb_client_id', sa.String(length=255), nullable=True))
    op.add_column('bank_accounts', sa.Column('bb_client_secret', sa.String(length=500), nullable=True))
    op.add_column('bank_accounts', sa.Column('bb_app_key', sa.String(length=255), nullable=True))
    op.add_column('bank_accounts', sa.Column('bb_sandbox', sa.Boolean(), nullable=True))
    # op.drop_index(op.f('uq_clientes_empresa_cpf_cnpj'), table_name='clientes')
    # op.create_index(op.f('ix_password_reset_tokens_cliente_id'), 'password_reset_tokens_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_password_reset_tokens_cliente_id'), table_name='password_reset_tokens_cliente')
    # op.create_index(op.f('uq_clientes_empresa_cpf_cnpj'), 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True)
    op.drop_column('bank_accounts', 'bb_sandbox')
    op.drop_column('bank_accounts', 'bb_app_key')
    op.drop_column('bank_accounts', 'bb_client_secret')
    op.drop_column('bank_accounts', 'bb_client_id')
    op.drop_column('bank_accounts', 'dias_baixa')
    op.drop_column('bank_accounts', 'dias_protesto')
    op.drop_column('bank_accounts', 'instrucao2')
    op.drop_column('bank_accounts', 'instrucao1')
    op.drop_column('bank_accounts', 'carteira_variacao')
    op.drop_column('bank_accounts', 'cnab_version')
    op.drop_column('bank_accounts', 'name')
    op.drop_column('bank_accounts', 'is_active')
    # ### end Alembic commands ###
