"""Add plan fields to Servico model

Revision ID: 2057c1341513
Revises: 312aa8aa761d
Create Date: 2025-11-25 13:10:31.916384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2057c1341513'
down_revision: Union[str, Sequence[str], None] = '312aa8aa761d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('upload_speed', sa.Float(), nullable=True))
    op.add_column('servicos', sa.Column('download_speed', sa.Float(), nullable=True))
    op.add_column('servicos', sa.Column('max_limit', sa.String(length=50), nullable=True))
    op.add_column('servicos', sa.Column('fidelity_months', sa.Integer(), nullable=True))
    op.add_column('servicos', sa.Column('billing_cycle', sa.String(length=20), nullable=True))
    op.add_column('servicos', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'notes')
    op.drop_column('servicos', 'billing_cycle')
    op.drop_column('servicos', 'fidelity_months')
    op.drop_column('servicos', 'max_limit')
    op.drop_column('servicos', 'download_speed')
    op.drop_column('servicos', 'upload_speed')
    # ### end Alembic commands ###
