"""add_created_at_updated_at_to_routers

Revision ID: 312aa8aa761d
Revises: 64d7f92f7890
Create Date: 2025-11-24 21:59:45.942429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312aa8aa761d'
down_revision: Union[str, Sequence[str], None] = '64d7f92f7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('routers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'updated_at')
    op.drop_column('routers', 'created_at')
    # ### end Alembic commands ###
