"""add bank_accounts

Revision ID: 3b029419c891
Revises: 7d032a0ae1f7
Create Date: 2025-11-30 11:40:29.598183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b029419c891'
down_revision: Union[str, Sequence[str], None] = '7d032a0ae1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('codigo_banco', sa.String(length=10), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('agencia_dv', sa.String(length=5), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('conta_dv', sa.String(length=5), nullable=True),
    sa.Column('titular', sa.String(length=255), nullable=True),
    sa.Column('cpf_cnpj_titular', sa.String(length=18), nullable=True),
    sa.Column('carteira', sa.String(length=50), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('nosso_numero_sequence', sa.Integer(), nullable=True),
    sa.Column('remittance_config', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('gateway_credentials', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.add_column('empresas', sa.Column('default_bank_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'bank_accounts', ['default_bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'default_bank_account_id')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
