"""Add promotional fields to Servico model

Revision ID: 3e3812829058
Revises: e6ae8c31bfae
Create Date: 2025-11-25 13:33:22.261188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3812829058'
down_revision: Union[str, Sequence[str], None] = 'e6ae8c31bfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('promotional_price', sa.Float(), nullable=True))
    op.add_column('servicos', sa.Column('promotional_months', sa.Integer(), nullable=True))
    op.add_column('servicos', sa.Column('promotional_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'promotional_active')
    op.drop_column('servicos', 'promotional_months')
    op.drop_column('servicos', 'promotional_price')
    # ### end Alembic commands ###
