"""Add BB specific fields to Receivable

Revision ID: 415f86c312a2
Revises: 158b24a98a89
Create Date: 2026-05-07 11:35:16.698846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415f86c312a2'
down_revision: Union[str, Sequence[str], None] = '158b24a98a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('uq_clientes_empresa_cpf_cnpj'), table_name='clientes')
    # op.create_index(op.f('ix_password_reset_tokens_cliente_id'), 'password_reset_tokens_cliente', ['id'], unique=False)
    op.add_column('receivables', sa.Column('bb_boleto_numero', sa.String(length=50), nullable=True))
    op.add_column('receivables', sa.Column('bb_boleto_url', sa.String(length=1000), nullable=True))
    op.add_column('receivables', sa.Column('bb_pix_qrcode', sa.Text(), nullable=True))
    op.add_column('receivables', sa.Column('bb_pix_txid', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receivables', 'bb_pix_txid')
    op.drop_column('receivables', 'bb_pix_qrcode')
    op.drop_column('receivables', 'bb_boleto_url')
    op.drop_column('receivables', 'bb_boleto_numero')
    # op.drop_index(op.f('ix_password_reset_tokens_cliente_id'), table_name='password_reset_tokens_cliente')
    # op.create_index(op.f('uq_clientes_empresa_cpf_cnpj'), 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
