"""add_logo_certificado_email_fields_to_empresas

Revision ID: 4ad0fb48ebe3
Revises: 2025_10_22_1100
Create Date: 2025-10-22 19:02:26.650363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad0fb48ebe3'
down_revision: Union[str, Sequence[str], None] = '2025_10_22_1100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('empresas', sa.Column('certificado_path', sa.String(length=500), nullable=True))
    op.add_column('empresas', sa.Column('certificado_senha', sa.String(length=500), nullable=True))
    op.add_column('empresas', sa.Column('smtp_server', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('smtp_password', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'empresas', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_users_active_empresa'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'empresas', ['active_empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_active_empresa'), 'users', 'empresas', ['active_empresa_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'smtp_password')
    op.drop_column('empresas', 'smtp_user')
    op.drop_column('empresas', 'smtp_port')
    op.drop_column('empresas', 'smtp_server')
    op.drop_column('empresas', 'certificado_senha')
    op.drop_column('empresas', 'certificado_path')
    op.drop_column('empresas', 'logo_url')
    # ### end Alembic commands ###
