"""Add address fields to nfcom table

Revision ID: 50db718178e9
Revises: 20251025_extend_servicos_add_nfcom_fields
Create Date: 2025-10-27 20:45:53.868663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50db718178e9'
down_revision: Union[str, Sequence[str], None] = '20251025_extend_servicos_add_nfcom_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfcom', sa.Column('dest_endereco', sa.String(length=255), nullable=True))
    op.add_column('nfcom', sa.Column('dest_numero', sa.String(length=20), nullable=True))
    op.add_column('nfcom', sa.Column('dest_complemento', sa.String(length=100), nullable=True))
    op.add_column('nfcom', sa.Column('dest_bairro', sa.String(length=100), nullable=True))
    op.add_column('nfcom', sa.Column('dest_municipio', sa.String(length=100), nullable=True))
    op.add_column('nfcom', sa.Column('dest_uf', sa.String(length=2), nullable=True))
    op.add_column('nfcom', sa.Column('dest_cep', sa.String(length=9), nullable=True))
    op.add_column('nfcom', sa.Column('dest_codigo_ibge', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfcom', 'dest_codigo_ibge')
    op.drop_column('nfcom', 'dest_cep')
    op.drop_column('nfcom', 'dest_uf')
    op.drop_column('nfcom', 'dest_municipio')
    op.drop_column('nfcom', 'dest_bairro')
    op.drop_column('nfcom', 'dest_complemento')
    op.drop_column('nfcom', 'dest_numero')
    op.drop_column('nfcom', 'dest_endereco')
    # ### end Alembic commands ###
