"""Initial migration

Revision ID: 786564105bb7
Revises: 
Create Date: 2025-10-21 21:54:16.563945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786564105bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('regime_tributario', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome_razao_social', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('FISICA', 'JURIDICA', name='tipopessoa'), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('usuario_empresa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'empresa_id')
    )
    op.create_table('cliente_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_enderecos_id'), 'cliente_enderecos', ['id'], unique=False)
    op.create_table('nfcom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.Integer(), nullable=False),
    sa.Column('serie', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('protocolo_autorizacao', sa.String(length=50), nullable=True),
    sa.Column('data_autorizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo_emissao', sa.Enum('NORMAL', 'CONTINGENCIA', name='tipoemissao'), nullable=False),
    sa.Column('finalidade_emissao', sa.Enum('NORMAL', 'SUBSTITUICAO', 'AJUSTE', name='finalidadeemissao'), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('valor_icms', sa.Float(), nullable=True),
    sa.Column('valor_pis', sa.Float(), nullable=True),
    sa.Column('valor_cofins', sa.Float(), nullable=True),
    sa.Column('informacoes_adicionais', sa.Text(), nullable=True),
    sa.Column('xml_gerado', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfcom_chave_acesso'), 'nfcom', ['chave_acesso'], unique=True)
    op.create_index(op.f('ix_nfcom_id'), 'nfcom', ['id'], unique=False)
    op.create_table('nfcom_faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfcom_id', sa.Integer(), nullable=False),
    sa.Column('numero_fatura', sa.String(length=50), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor_fatura', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nfcom_id'], ['nfcom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfcom_faturas_id'), 'nfcom_faturas', ['id'], unique=False)
    op.create_table('nfcom_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfcom_id', sa.Integer(), nullable=False),
    sa.Column('codigo_servico', sa.String(length=50), nullable=False),
    sa.Column('descricao_servico', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('base_calculo_icms', sa.Float(), nullable=True),
    sa.Column('aliquota_icms', sa.Float(), nullable=True),
    sa.Column('valor_icms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfcom_id'], ['nfcom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfcom_itens_id'), 'nfcom_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nfcom_itens_id'), table_name='nfcom_itens')
    op.drop_table('nfcom_itens')
    op.drop_index(op.f('ix_nfcom_faturas_id'), table_name='nfcom_faturas')
    op.drop_table('nfcom_faturas')
    op.drop_index(op.f('ix_nfcom_id'), table_name='nfcom')
    op.drop_index(op.f('ix_nfcom_chave_acesso'), table_name='nfcom')
    op.drop_table('nfcom')
    op.drop_index(op.f('ix_cliente_enderecos_id'), table_name='cliente_enderecos')
    op.drop_table('cliente_enderecos')
    op.drop_table('usuario_empresa')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
