"""Add router interfaces and IP classes

Revision ID: 9c8c75845a9d
Revises: 458b6df5c30c
Create Date: 2025-11-25 16:10:01.009057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c8c75845a9d'
down_revision: Union[str, Sequence[str], None] = '458b6df5c30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicos_contratados', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ATIVO', 'SUSPENSO', 'CANCELADO', 'PENDENTE_INSTALACAO', name='statuscontrato'),
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'"))
    op.alter_column('servicos_contratados', 'tipo_conexao',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('FIBRA', 'RADIO', 'CABO', 'SATELITE', 'ADSL', 'OUTRO', name='tipoconexao'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicos_contratados', 'tipo_conexao',
               existing_type=sa.Enum('FIBRA', 'RADIO', 'CABO', 'SATELITE', 'ADSL', 'OUTRO', name='tipoconexao'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('servicos_contratados', 'status',
               existing_type=sa.Enum('ATIVO', 'SUSPENSO', 'CANCELADO', 'PENDENTE_INSTALACAO', name='statuscontrato'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'"))
    # ### end Alembic commands ###
