"""Add is_active field to ip_pools table

Revision ID: b8a1c8f5a979
Revises: 20251127_1149
Create Date: 2025-11-27 12:47:43.866738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a1c8f5a979'
down_revision: Union[str, Sequence[str], None] = '20251127_1149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_pools', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_pools', 'is_active')
    # ### end Alembic commands ###
