"""update_router_fields

Revision ID: c5bb756af08a
Revises: 3d86534c2591
Create Date: 2025-11-24 18:54:21.458560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5bb756af08a'
down_revision: Union[str, Sequence[str], None] = '3d86534c2591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('nome', sa.String(length=100), nullable=False))
    op.add_column('routers', sa.Column('ip', sa.String(length=15), nullable=False))
    op.add_column('routers', sa.Column('usuario', sa.String(length=100), nullable=False))
    op.add_column('routers', sa.Column('senha', sa.String(length=255), nullable=False))
    op.add_column('routers', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('routers', sa.Column('porta', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_routers_name'), table_name='routers')
    op.create_index(op.f('ix_routers_nome'), 'routers', ['nome'], unique=False)
    op.drop_column('routers', 'ip_address')
    op.drop_column('routers', 'encrypted_password')
    op.drop_column('routers', 'name')
    op.drop_column('routers', 'username')
    op.drop_column('routers', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routers', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('routers', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('routers', sa.Column('encrypted_password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('routers', sa.Column('ip_address', mysql.VARCHAR(length=15), nullable=False))
    op.drop_index(op.f('ix_routers_nome'), table_name='routers')
    op.create_index(op.f('ix_routers_name'), 'routers', ['name'], unique=False)
    op.drop_column('routers', 'porta')
    op.drop_column('routers', 'tipo')
    op.drop_column('routers', 'senha')
    op.drop_column('routers', 'usuario')
    op.drop_column('routers', 'ip')
    op.drop_column('routers', 'nome')
    # ### end Alembic commands ###
