"""Add endereco_id to ServicoContratado

Revision ID: cb2214986b53
Revises: 0fd7e7f85789
Create Date: 2026-05-15 10:45:46.430950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb2214986b53'
down_revision: Union[str, Sequence[str], None] = '0fd7e7f85789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ativos_contrato', 'tipo_equipamento',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='ROTEADOR, ONT, BRIDGE, RADIO, etc',
               existing_nullable=False)
    op.alter_column('ativos_contrato', 'login_acesso',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Login para acesso técnico/manutenção',
               existing_nullable=True)
    op.alter_column('ativos_contrato', 'senha_acesso',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Senha para acesso técnico/manutenção',
               existing_nullable=True)
    op.create_index(op.f('ix_ativos_contrato_id'), 'ativos_contrato', ['id'], unique=False)
    op.drop_index(op.f('uq_clientes_empresa_cpf_cnpj'), table_name='clientes')
    op.create_index(op.f('ix_password_reset_tokens_cliente_id'), 'password_reset_tokens_cliente', ['id'], unique=False)
    op.drop_index(op.f('idx_receivables_payment_token'), table_name='receivables')
    op.create_index(op.f('ix_receivables_payment_token'), 'receivables', ['payment_token'], unique=True)
    op.alter_column('routers', 'metodo_autenticacao_padrao',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RADIUS', 'PPPOE', 'HOTSPOT', 'IP_MAC', name='metodoautenticacaorouter'),
               existing_comment='Define se o roteador usa RADIUS, PPPoE local, Hotspot ou IP/MAC',
               existing_nullable=True)
    op.add_column('servicos_contratados', sa.Column('endereco_id', sa.Integer(), nullable=True))
    op.alter_column('servicos_contratados', 'metodo_autenticacao',
               existing_type=mysql.ENUM('IP_MAC', 'PPPOE', 'HOTSPOT', 'RADIUS'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('servicos_contratados', 'assinatura_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.drop_index(op.f('idx_assinatura_token'), table_name='servicos_contratados')
    op.create_index(op.f('ix_servicos_contratados_assinatura_token'), 'servicos_contratados', ['assinatura_token'], unique=True)
    op.drop_constraint(op.f('fk_servicos_contratados_ip_class_id'), 'servicos_contratados', type_='foreignkey')
    op.create_foreign_key(None, 'servicos_contratados', 'empresa_cliente_enderecos', ['endereco_id'], ['id'])
    op.create_foreign_key(None, 'servicos_contratados', 'ip_classes', ['ip_class_id'], ['id'], ondelete='SET NULL')
    op.drop_column('servicos_contratados', 'observacoes_instalacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos_contratados', sa.Column('observacoes_instalacao', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'servicos_contratados', type_='foreignkey')
    op.drop_constraint(None, 'servicos_contratados', type_='foreignkey')
    op.create_foreign_key(op.f('fk_servicos_contratados_ip_class_id'), 'servicos_contratados', 'ip_classes', ['ip_class_id'], ['id'])
    op.drop_index(op.f('ix_servicos_contratados_assinatura_token'), table_name='servicos_contratados')
    op.create_index(op.f('idx_assinatura_token'), 'servicos_contratados', ['assinatura_token'], unique=True)
    op.alter_column('servicos_contratados', 'assinatura_data',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('servicos_contratados', 'metodo_autenticacao',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('IP_MAC', 'PPPOE', 'HOTSPOT', 'RADIUS'),
               existing_nullable=True)
    op.drop_column('servicos_contratados', 'endereco_id')
    op.alter_column('routers', 'metodo_autenticacao_padrao',
               existing_type=sa.Enum('RADIUS', 'PPPOE', 'HOTSPOT', 'IP_MAC', name='metodoautenticacaorouter'),
               type_=mysql.VARCHAR(length=20),
               existing_comment='Define se o roteador usa RADIUS, PPPoE local, Hotspot ou IP/MAC',
               existing_nullable=True)
    op.drop_index(op.f('ix_receivables_payment_token'), table_name='receivables')
    op.create_index(op.f('idx_receivables_payment_token'), 'receivables', ['payment_token'], unique=True)
    op.drop_index(op.f('ix_password_reset_tokens_cliente_id'), table_name='password_reset_tokens_cliente')
    op.create_index(op.f('uq_clientes_empresa_cpf_cnpj'), 'clientes', ['empresa_id', 'cpf_cnpj'], unique=True)
    op.drop_index(op.f('ix_ativos_contrato_id'), table_name='ativos_contrato')
    op.alter_column('ativos_contrato', 'senha_acesso',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='Senha para acesso técnico/manutenção',
               existing_nullable=True)
    op.alter_column('ativos_contrato', 'login_acesso',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               comment='Login para acesso técnico/manutenção',
               existing_nullable=True)
    op.alter_column('ativos_contrato', 'tipo_equipamento',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='ROTEADOR, ONT, BRIDGE, RADIO, etc',
               existing_nullable=False)
    # ### end Alembic commands ###
