"""Update models for NFCom layout compliance

Revision ID: d3a5e4bf5d03
Revises: da0e3d37c8e8
Create Date: 2025-10-24 17:57:49.349159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3a5e4bf5d03'
down_revision: Union[str, Sequence[str], None] = 'da0e3d37c8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('idOutros', sa.String(length=20), nullable=True))
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=18),
               nullable=True)
    op.create_index(op.f('ix_clientes_idOutros'), 'clientes', ['idOutros'], unique=False)
    op.add_column('nfcom', sa.Column('cMunFG', sa.String(length=7), nullable=False))
    op.add_column('nfcom', sa.Column('tpFat', sa.Enum('NORMAL', 'CENTRALIZADO', 'COFATURAMENTO', name='tipofaturamento'), nullable=False))
    op.add_column('nfcom_itens', sa.Column('cClass', sa.String(length=7), nullable=False))
    op.add_column('nfcom_itens', sa.Column('valor_desconto', sa.Float(), nullable=True))
    op.add_column('nfcom_itens', sa.Column('valor_outros', sa.Float(), nullable=True))
    op.alter_column('nfcom_itens', 'codigo_servico',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('nfcom_itens', 'descricao_servico',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfcom_itens', 'descricao_servico',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('nfcom_itens', 'codigo_servico',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.drop_column('nfcom_itens', 'valor_outros')
    op.drop_column('nfcom_itens', 'valor_desconto')
    op.drop_column('nfcom_itens', 'cClass')
    op.drop_column('nfcom', 'tpFat')
    op.drop_column('nfcom', 'cMunFG')
    op.drop_index(op.f('ix_clientes_idOutros'), table_name='clientes')
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=18),
               nullable=False)
    op.drop_column('clientes', 'idOutros')
    # ### end Alembic commands ###
