"""Add codigo_ibge to empresas table

Revision ID: df224ecc7d28
Revises: 786564105bb7
Create Date: 2025-10-22 02:17:53.076179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df224ecc7d28'
down_revision: Union[str, Sequence[str], None] = '786564105bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('codigo_ibge', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'codigo_ibge')
    # ### end Alembic commands ###
