"""Add tipo field to Servico model

Revision ID: e6ae8c31bfae
Revises: 2057c1341513
Create Date: 2025-11-25 13:22:09.176885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ae8c31bfae'
down_revision: Union[str, Sequence[str], None] = '2057c1341513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already added in previous run, just set defaults
    op.execute("UPDATE servicos SET tipo = 'SERVICO' WHERE tipo IS NULL OR tipo = ''")
    op.alter_column('servicos', 'tipo', existing_type=sa.String(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'tipo')
    # ### end Alembic commands ###
