"""Add is_active field to ppp_profiles table

Revision ID: f509b29332e4
Revises: ff73b3eeabe2
Create Date: 2025-11-27 12:52:44.254175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f509b29332e4'
down_revision: Union[str, Sequence[str], None] = 'ff73b3eeabe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppp_profiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppp_profiles', 'is_active')
    # ### end Alembic commands ###
