"""Set default value for is_active column in ip_pools

Revision ID: ff73b3eeabe2
Revises: b8a1c8f5a979
Create Date: 2025-11-27 12:49:45.626588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff73b3eeabe2'
down_revision: Union[str, Sequence[str], None] = 'b8a1c8f5a979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
